spring:
  profiles: local
greeting: Hello! Here's Local edit!
---
spring:
  profiles: dev
greeting: Hello! Here's Dev!
---
spring:
  profiles: stg
greeting: Hello! Here's Stg!
---
spring:
  profiles: prod
greeting: Hello! Here's Prod!
